### ISSUE TITLE
Should it be deeply nested

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/hist#1]
[μproot](https://github.com/scikit-hep/uproot) has a deeply nested feature. Considering that we can only access bin by `h[i, j]` currently, should we add this feature, too?

> This file is deeply nested, so while you could find the TTree with
>
> ```python
> file["one"]["two"]["tree"]
> # <TTree b'tree' at 0x7f37581297f0>
> ```
>
> you can also find it using a directory path, with slashes.
>
> ```python
> file["one/two/tree"]
> # <TTree b'tree' at 0x7f37504e4748>
> ```

**Comment by henryiii** [comment]
Nesting doesn't make as much sense for histograms. It doesn't work with numerical bins (`h[3/2]` ?) and doesn't even make sense with named bins (`'h['one/two']` should return what, exactly?). A histogram is a "rectangular" structure (product of dimensions), rather than a nested list.

It's good to be thinking about useful shortcuts, though!
