### ISSUE TITLE
[BUG] Uncertainty bands in efficiency ratios go above unity

### ISSUE THREAD

**Issue by dantrim** [scikit-hep/hist#277]
**Describe the bug**

The error bars produced in the ratio of an efficiency style plot (`hist.plot_ratio(..., rp_uncertainty_type = "poisson-ratio", ...)`)
can extend above unity. This is unexpected and not meaningful if the numerator is a true subset of the denominator.

**Steps to reproduce**

This is observed using `hist==2.4.0`.

Following the example from the [docs](https://hist.readthedocs.io/en/latest/user-guide/notebooks/Plots.html),

```python
hist0 = hist.Hist(hist.axis.Regular(50, -5, 5), underflow = False, overflow = False).fill(np.random.normal(size=1700))
hist1 = hist0.copy() * 0.98

fig = plt.figure(figsize = (10,8))
_ = hist1.plot_ratio(
    hist0,
    rp_ylabel="Efficiency",
    rp_num_label="hist1",
    rp_denom_label="hist0",
    rp_uncert_draw_type="line",
    rp_uncertainty_type="poisson-ratio",
    rp_ylim=[0.9,1.1],
)
```
This produces something like the following,
<img width="863" alt="image" src="https://user-images.githubusercontent.com/7841565/128089782-f1bd705c-50d2-443f-8daa-5375bf853cab.png">

where we see the error bars going above unity.

If I take the same data used in `hist0` and `hist1` above, and produce a `TEfficiency` object in `ROOT`, I get something like the following,
<img width="615" alt="image" src="https://user-images.githubusercontent.com/7841565/128089882-973ec586-83be-4891-9b44-332830c0ac6c.png">
which is something more like what I would expect since I believe `hist` is using a Clopper-Pearson interval (default in ROOT).

**Comment by matthewfeickert** [comment]
Thanks @dantrim. I'll try to get to this tonight (or at least soon). This will either require some changes to 

https://github.com/scikit-hep/hist/blob/a19dbbc7916166156ec44363157f1cce7eae741d/src/hist/intervals.py#L113-L117

to limit the values for the `clopper_pearson_interval`

https://github.com/scikit-hep/hist/blob/a19dbbc7916166156ec44363157f1cce7eae741d/src/hist/intervals.py#L141-L143

or just hanges to the plotting code. 

cc @nsmith- for thoughts on how `coffea` approaches this.

**Comment by nsmith-** [comment]
The `poisson-ratio` uncertainty type is supposed to be for when you are dividing data points that are assumed to come from two *independent* Poisson distributions, whereas the `efficiency` uncertainty type assumes the numerator is a subset of the denominator. Looking at the source of https://github.com/scikit-hep/hist/blob/a19dbbc7916166156ec44363157f1cce7eae741d/src/hist/intervals.py#L141-L143 it appears this is incorrectly implemented. For `uncertainty_type == "efficiency"` one should use `clopper_pearson_interval(num, denom)`.

**Comment by dantrim** [comment]
Thanks @nsmith- and @matthewfeickert. So it looks like the correct behavior, then, is that `efficiency` should **not** be an alias for `poisson-ratio` as [here](https://github.com/scikit-hep/hist/blob/a19dbbc7916166156ec44363157f1cce7eae741d/src/hist/intervals.py#L141).

**Comment by matthewfeickert** [comment]
Yeah, I got this wrong when I implemented it. Thanks for finding this @dantrim and for pointing out the fix @nsmith-.

**Comment by nsmith-** [comment]
Also, while we're here, since I wrote `# poisson ratio n/m is equivalent to binomial n/(n+m)` in the original coffea code, I think it needs some supporting documents. Strangely I don't recall where I found it, though there is plenty of literature for confidence intervals of poisson ratios, e.g. [here](https://www.newton.ac.uk/files/preprints/ni13040.pdf) or [here](https://ttu-ir.tdl.org/bitstream/handle/2346/59954/31295007034522.pdf?sequence=1), and also this [SO post](https://stats.stackexchange.com/questions/10951/what-is-the-distribution-of-the-ratio-of-two-poisson-random-variables) explaining how to redefine it to even be measurable :) Anyway,

Let n ~ Poisson(lambda_n), m ~ Poisson(lambda_m), then for p = lambda_n / (lambda_n + lambda_m) one can show that the joint probability mass function Poisson(n; lambda_n) * Poisson(m; lambda_m) = Binom(n; n+m, p) * Poisson(n+m; lambda_n + lambda_m). Then the usual [Clopper-Pearson](https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval#Clopper%E2%80%93Pearson_interval) confidence interval can be used as an estimator of p conditioned on n+m (as is usual). If we instead want to estimate r = lambda_n / lambda_m, then since r = p / (1-p) is monotone increasing, the same confidence interval can be rescaled and still have _at least as good_ coverage properties, though almost surely it begins to overcover.

Though, this means that the `poisson-ratio` implementation is also buggy: it is missing the rescaling:
```python
p_lim = clopper_pearson_interval(num, num + denom)
r_lim = p_lim / (1 - p_lim)  # also need to handle edge cases (corresponds to divide by 0)
ratio_uncert = np.abs(r_lim - ratio) 
```

**Comment by matthewfeickert** [comment]
Thanks @nsmith- (also sorry for not catching any of this sooner). I've migrated that to Issue #279 so we can get this closed, but we should get to fixing it soon too.
