### ISSUE TITLE
[BUG] Fix poisson-ratio implementation for uncertainty intervals

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/hist#279]
Also, while we're here, since I wrote `# poisson ratio n/m is equivalent to binomial n/(n+m)` in the original coffea code, I think it needs some supporting documents. Strangely I don't recall where I found it, though there is plenty of literature for confidence intervals of poisson ratios, e.g. [here](https://www.newton.ac.uk/files/preprints/ni13040.pdf) or [here](https://ttu-ir.tdl.org/bitstream/handle/2346/59954/31295007034522.pdf?sequence=1), and also this [SO post](https://stats.stackexchange.com/questions/10951/what-is-the-distribution-of-the-ratio-of-two-poisson-random-variables) explaining how to redefine it to even be measurable :) Anyway,

Let n ~ Poisson(lambda_n), m ~ Poisson(lambda_m), then for p = lambda_n / (lambda_n + lambda_m) one can show that the joint probability mass function Poisson(n; lambda_n) * Poisson(m; lambda_m) = Binom(n; n+m, p) * Poisson(n+m; lambda_n + lambda_m). Then the usual [Clopper-Pearson](https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval#Clopper%E2%80%93Pearson_interval) confidence interval can be used as an estimator of p conditioned on n+m (as is usual). If we instead want to estimate r = lambda_n / lambda_m, then since r = p / (1-p) is monotone increasing, the same confidence interval can be rescaled and still have _at least as good_ coverage properties, though almost surely it begins to overcover.

Though, this means that the `poisson-ratio` implementation is also buggy: it is missing the rescaling:
```python
p_lim = clopper_pearson_interval(num, num + denom)
r_lim = p_lim / (1 - p_lim)  # also need to handle edge cases (corresponds to divide by 0)
ratio_uncert = np.abs(r_lim - ratio) 
```

_Originally posted by @nsmith- in https://github.com/scikit-hep/hist/issues/277#issuecomment-892703615_

**Comment by nsmith-** [comment]
More fun:
```python
from hist.intervals import clopper_pearson_interval
import scipy.stats
import numpy as np
import matplotlib.pyplot as plt

trials = 10000
pts = 30
lambda_n, lambda_m = np.meshgrid(np.geomspace(0.1, 1000, pts), np.geomspace(0.1, 1000, pts))
r = lambda_n / lambda_m
n = scipy.stats.poisson.rvs(lambda_n, size=(trials, pts, pts))
m = scipy.stats.poisson.rvs(lambda_m, size=(trials, pts, pts))
p_lim = clopper_pearson_interval(n, n + m)

with np.errstate(divide="ignore"):
    r_lim = p_lim / (1 - p_lim)

coverage = np.sum((r_lim[0] <= r) & (r <= r_lim[1]), axis=0) / trials

fig, ax = plt.subplots()
levels = [0.5, 0.683, 0.954, 1.0]
cs = ax.contourf(lambda_n, lambda_m, coverage, levels=levels)

ax.set_xscale("log")
ax.set_yscale("log")
ax.set_xlabel("$\lambda_n$")
ax.set_ylabel("$\lambda_m$")
ax.legend(
    [
        plt.Rectangle((0, 0), 1, 1, fc=patch.get_facecolor()[0])
        for patch in cs.collections
    ],
    [f"$C \geq {level}$" for level in levels],
    title="Coverage"
)
```
![coverage](https://user-images.githubusercontent.com/6587412/128214723-03942793-e0ee-42b8-9437-abc69c2a35e9.png)

So the default desired coverage (0.68) seems to be achieved everywhere except when the true numerator is very low. Seeing this, I suspected a bug and sure enough doing a coverage test for just a binomial distribution shows the same issue:
 
```python
trials = 10000
pts = 30
p, n = np.meshgrid(np.linspace(0, 1, pts), np.geomspace(1, 1000, pts+1).astype(int))
k = scipy.stats.binom.rvs(n, p, size=(trials, pts+1, pts))
p_lim = clopper_pearson_interval(k, n)
coverage = np.sum((p_lim[0] <= p) & (p <= p_lim[1]), axis=0) / trials
```
![coverage_cp](https://user-images.githubusercontent.com/6587412/128214959-2dbb690b-f885-4133-9925-21fee2b68921.png)

The problem is that I incorrectly zero out the upper limit when the numerator is zero in https://github.com/scikit-hep/hist/blob/a19dbbc7916166156ec44363157f1cce7eae741d/src/hist/intervals.py#L108
Fixing that to `interval[0, num == 0.0] = 0.0`, I get
![coverage_cp](https://user-images.githubusercontent.com/6587412/128215098-b05b3ce7-ada1-4a70-a7d0-b51c3c8467c9.png)
for the efficiency and
![coverage](https://user-images.githubusercontent.com/6587412/128215140-6609ef2b-38c5-44ba-89f0-393c8af3f593.png)
for the poisson ratio coverage.

**Comment by matthewfeickert** [comment]
This is _super_ helpful @nsmith- &mdash; thank you for this!
