### ISSUE TITLE
[BUG] plot_ratio shouldn't require Minuit?

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/hist#290]
It seems the try/except is a bit earlier than it needs to be

https://github.com/scikit-hep/hist/blob/6544230fb517853b705c13275df267d6674eb2ac/src/hist/plot.py#L527

@matthewfeickert

**Comment by matthewfeickert** [comment]
I guess it depends. `plot_ratio` calls `_plot_ratiolike`

https://github.com/scikit-hep/hist/blob/6544230fb517853b705c13275df267d6674eb2ac/src/hist/basehist.py#L465

which calls `_fit_callable_to_hist`

https://github.com/scikit-hep/hist/blob/6544230fb517853b705c13275df267d6674eb2ac/src/hist/plot.py#L613

which calls `_curve_fit_wrapper`

https://github.com/scikit-hep/hist/blob/6544230fb517853b705c13275df267d6674eb2ac/src/hist/plot.py#L311

which uses Minuit

https://github.com/scikit-hep/hist/blob/6544230fb517853b705c13275df267d6674eb2ac/src/hist/plot.py#L172

So the suggestion is that instead of ensuring that all the dependencies needed from the `plot` extra

https://github.com/scikit-hep/hist/blob/6544230fb517853b705c13275df267d6674eb2ac/setup.py#L12-L17

are installed at the first possible function call to move them deeper to where they are first used

https://github.com/scikit-hep/hist/blob/6544230fb517853b705c13275df267d6674eb2ac/src/hist/plot.py#L155-L156

?

I'm not opposed to that in anyway, but it does mean that users could call `plot_ratio` once and have things work, and then later on call `plot_ratio` and get an error which could be confusing to them (though I guess the raised exception message could clear up why). However if you do this then you would lose the high level information on what view is asking for it

https://github.com/scikit-hep/hist/blob/6544230fb517853b705c13275df267d6674eb2ac/src/hist/plot.py#L531

Thoughts @henryiii?

**Comment by henryiii** [comment]
If you give it something that that doesn't require fitting, it doesn't seem right to still require that iMinuit be installed. So I'd be for it, I think.
